# Site settings
title:       ./Fdll14Notes
email:       shuro.fadhillah@gmail.com
author:      Muhamad Shuro Fadhillah
description: "Just blogging and learn the code."
baseurl:     ""
url:         "http://fdll14.github.io"

google_analytics:
animated:           true
show_related_posts: true
show_post_footers:  false
show_social_icons:  false
disqus_shortname: fdll_14
github_username: fdll14
stackoverflow_id:
twitter_username: Fdll_14
google_plus_id: 
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
