# Site settings
title:       ./insan06
email:       insanmaulana4483@gmail.com
author:      Insan Maulana
description: "Just blogging and learn the code."
baseurl:     ""
url:         "http://insan.github.io"

google_analytics:
animated:           true
show_related_posts: true
show_post_footers:  false
show_social_icons:  false
disqus_shortname: 
github_username: insan06
stackoverflow_id:
twitter_username: 
google_plus_id: 
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
